services:
  - type: web
    name: cogio-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python cogio_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
